### ISSUE TITLE
Feature suggestion: Make `Url` and `Img` context-aware

### ISSUE THREAD

**Issue by dpprdan** [ThinkR-open/remedy#1]
IMO, the default for inserting a URL (e.g. also here on Github) is to mark the link text, click on the URL button and then insert the URL (mostly copy & paste, at least for me). I.e. the selected text is put in the square brackets and not in the round brackets. 

`remedy::urlr`(and `imager`) does this the other way around, however.

So how about making `Url` and `Img` context-aware, i.e. if the selection is a "URL" (if it contains a period, to catch internal links as well?), put it in the round brackets and set the curser between the square brackets. Else, use the selection as the link text, i.e. put it in square brackets and the curser between round brackets. 
(Exception: if the selection is empty, handle it like a URL, i.e. cursor in square brackets).

**Comment by ColinFay** [comment]
issues fixed in @jonmcalder pull request
