### ISSUE TITLE
merging chunky

### ISSUE THREAD

**Issue by yonicd** [ThinkR-open/remedy#14]
how do you want to merge the two pkgs?

https://github.com/yonicd/chunky

**Comment by ColinFay** [comment]
hi @yonicd ! 

Thanks for reaching out. 

You can either send a PR to the repo, adding the code and your name in the DESCRIPTION file, or I'll take care of that.

As you wish :)

**Comment by yonicd** [comment]
ok. the `addin` works a bit differently than others that are out there. i've gone the route of passing params to the `addin` via `opts$get()`/`opts$set()` like in the `knitr` pkg. it gets around how the IDE is set up and lets the user work w the `addin` like any other fn.
