### ISSUE TITLE
Wrapper to put YouTube video in a Rmd

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/remedy#19]
Something that could do : 

```r
remedy::youtube("url/youtube") 
```

and that would be converted an html frame when knitted .

**Comment by yonicd** [comment]
That can be done via clipr and youtube link

**Comment by yonicd** [comment]
added https://github.com/ThinkR-open/remedy/commit/066898fe9139a53fe92ff40d7abbe2f5f8febf6c
