### ISSUE TITLE
Request insertion of html comments for text

### ISSUE THREAD

**Issue by HJAllen** [ThinkR-open/remedy#22]
A feature i would find useful is an insert of html comment tags in markdown text outside of a chunk with the cursor landing inside, ready for typing as in:
`<!-- 'cursor lands here' -->`
Thanks!

**Comment by yonicd** [comment]
that's already built in to rmd's. highlight the script you want to comment as html and do keyboard shortcut as you would in an R file.

**Comment by HJAllen** [comment]
Thanks for the quick response! That will place the entire line within the comment tags. I am looking for a quick way to be able to insert an editorial comment within a line of text.
Using the ctrl+shift+c i get
`<!--This is clear as mud. Mud can be opaque-->`
but would find this more useful.
`This is clear as mud<!--please clarify preceeding statement-->. Mud can be opaque`

**Comment by yonicd** [comment]
ah. ok. that makes more sense.

**Comment by HJAllen** [comment]
Another thought is to include a time-date tag. This may not be as useful in contexts other than editorial comments. Perhaps a global option?

**Comment by HJAllen** [comment]
function to insert html comment


`
htmlComment <- function(){
  a <- rstudioapi::getSourceEditorContext()
  if(!identical(a$selection[[1]]$text, "")){
    rstudioapi::insertText(location = a$selection[[1]]$range, text = paste0(""))
  }else{
    rstudioapi::insertText(location = a$selection[[1]]$range, text = "")
    rstudioapi::setCursorPosition(position = c(row = a$selection[[1]]$range$start["row"],
                                               column = a$selection[[1]]$range$start["column"] + 5))
  }
}
`
and in addins.dcf
`Name: HTML Comment
Description: Convert selected text into an HTML comment or insert new comment
Binding: htmlComment
Interactive: false`

**Comment by yonicd** [comment]
your request was added. see function help (`?remedy::htmlcommentr`) for usage details

thank you for the suggested addin.

https://github.com/ThinkR-open/remedy/commit/e830fafae3e61895f91536ef1d09b6022cfc5d65
