### ISSUE TITLE
Suggestion: add default hotkeys for Windows too

### ISSUE THREAD

**Issue by AndreaPi** [ThinkR-open/remedy#24]
Hi,

your package is brilliant, but as far as I understand, currently `remedy::set_hotkeys` works only on iOS (right?). Would it be possible to extend it so that it defines a set of hotkeys on iOS, and another on Windows? Of course, if determining the operating system at runtime is hard, even just an argument  `remedy::set_hotkeys(os = c("Windows", "iOS")` would be great. Thanks!

**Comment by yonicd** [comment]
there is a new [package](https://github.com/yonicd/rsam) to control the hotkeys in RStudio that is OS agnostic ( and is the extension of what set_hotkeys does). In the future this functionality in remedy will just be ported to [rsam](https://github.com/yonicd/rsam) and depend on it probably.

**Comment by AndreaPi** [comment]
Thanks! Just to be sure, does this mean if I install `rsam, it willsetup `remedy` hotkeys for me? Or do you mean it will do that in a future release?

**Comment by yonicd** [comment]
in the (near) future. for now you can run either the rsam addin that manages addins and their hotkeys for you or in command line for batch setup.

```
mac_keys <- remedy::remedy_opts$get('hotkeys')
win_ keys <- YOUR_WIN_KEYS #same length as fns

fns <- sprintf('remedy::%sr',names(mac_keys))

rsam::set_shortcut(fn = fns, shortcut = mac_keys) #if in windows use win_keys
```

you can use the KEYS validation in `rsam` to safely build key your own combinations

for example:

```
key <- KEYS$`left command/window key` + KEYS$shift + KEYS$i

key
#> [1] "Command+Shift+I"

#or 

base_key <- KEYS$`left command/window key`
base_key + KEYS[2:9]
# [1] "Command+0" "Command+1" "Command+2" "Command+3" "Command+4" "Command+5" "Command+6" "Command+7"
```

**Comment by AndreaPi** [comment]
Thanks! I'll check and close the issue

**Comment by yonicd** [comment]
btw if you have any suggestions for hotkey combinations on windows for the remedy addins, we would be happy to adopt them.

**Comment by AndreaPi** [comment]
@yonicd I think just substituting the `Cmd` key with the `Windows` key should work. Anyway I'm going to make a few tests in these weeks and let you know.

**Comment by AndreaPi** [comment]
Hmm, I tried the following:

```
win_keys <- remedy::remedy_opts$get('hotkeys')
win_keys["backtick"] <- KEYS$ctrl+KEYS$`left command/window key`+KEYS$add
fns <- sprintf('remedy::%sr',names(win_keys))
set_shortcut(fn = fns, shortcut = win_keys)

```

But I got:

`* Addin shortcuts unchanged`

As a matter of fact, the hotkey for `backtick` hasn't changed. I also have an issue with `rsam` - opened an issue there.

**Comment by yonicd** [comment]
as a safeguard rsam wont override any setting if it already exists for an addin. you need to explicitly tell it to override. the `KEYS$add` doesn't make sense really because you would need a shift to get to it. 

```r
win_keys <- remedy::remedy_opts$get('hotkeys')
win_keys["backtick"] <- KEYS$ctrl+KEYS$`left command/window key`+ KEYS$`equal sign`
fns <- sprintf('remedy::%sr',names(win_keys))
set_shortcut(fn = fns, shortcut = win_keys, override=TRUE)
# * The following addin keyboard shorcuts were set, restart RStudio to initialize
# remedy::backtickr = Ctrl+Command+=
```

**Comment by AndreaPi** [comment]
Hey sorry for leaving this open but I've been extremely busy this days and couldn't check your solution. I'll do it by the end of the week. the KEYS$add can be reached without shift on my keyboard (ah, locales...:relaxed:). It was only an example anyway, it's not my final layout.

**Comment by AndreaPi** [comment]
Hey sorry for leaving this open but I've been extremely busy this days and couldn't check your solution. I'll do it by the end of the week. the KEYS$add can be reached without shift on my keyboard (ah, locales...:relaxed:). It was only an example anyway, it's not my final layout.

**Comment by yonicd** [comment]
no hurry. thanks for testing.

**Comment by AndreaPi** [comment]
In the end I found it much better to use a Mac (not only for `remedy`, of course :-), so I won't be working on the Windows shortcuts anymore (couldn't test them anyway). BTW, I found it really hard to assign them with getting a conflict with some RStudio or system-wide hotkey! The iOS hotkey space seems less polluted and/or better organized
