### ISSUE TITLE
Feature Request: Comment Barrier

### ISSUE THREAD

**Issue by HJAllen** [ThinkR-open/remedy#26]
An addin to insert a Comment Barrier would be nice for organizing code.

`
commentBarrier <- function(){
 a <- rstudioapi::getSourceEditorContext()
if(!identical(a$selection[[1]]$text, "")){
 rstudioapi::insertText(location = a$selection[[1]]$range,
 text = paste0("########################################\n#",
 a$selection[[1]]$text, "\n########################################\n"))
}else{
 rstudioapi::insertText(location = a$selection[[1]]$range, text = "########################################\n")
 rstudioapi::setCursorPosition(position = c(row = a$selection[[1]]$range$start["row"], column = a$selection[[1]]$range$start["column"] + 5)) } }
`
and in addins.dcf
`
Name: Comment Barrier Description: Convert selected text into comment block with barrier or insert new comment barrier
Binding: commentBarrier
Interactive: false
`

**Comment by ColinFay** [comment]
Hi @HJAllen, 

Is the implementation you're looking for the same as https://github.com/ThinkR-open/littleboxes ?

**Comment by HJAllen** [comment]
Yes thanks!
