### ISSUE TITLE
Feature request: Add session_info

### ISSUE THREAD

**Issue by dpprdan** [ThinkR-open/remedy#27]
Add a shortcut to insert session_info (similar to the reprex 📦)?

````
<details><summary>Session info</summary>  
```{r}
devtools::session_info()
```
</details>
````

**Comment by ColinFay** [comment]
Hi @dpprdan 

Thanks for the suggestion.

As @yonicd mentioned in #28, {remedy} is more about manipulating existing markdown than inserting elements. 

You should definitely have a look at rsam (https://github.com/yonicd/rsam), that will allow you to create this kind of addin. 

Best, 
Colin

**Comment by dpprdan** [comment]
Thanks @ColinFay and sorry for the late reply. 

I wasn't entirely sure myself, whether this would fit into the package, so this is totally fine. I'll have a look at rsam, but for now keeping this in my fork of remedy seems like the easiest option. ;)
