### ISSUE TITLE
Running `remedy::set_hotkeys()` on Mac has no effect

### ISSUE THREAD

**Issue by aoles** [ThinkR-open/remedy#30]
Hi,
The function for setting key bindings doesn't seem to work for me. After running `remedy::set_hotkeys()` and restarting RStudio no key bindings are added, even setting `overide = TRUE` doesn't help. Observed on Mac under RStudio 1.1.453.

Cheers,
Andrzej

**Comment by yonicd** [comment]
the functionality in remedy for the hotkeys was ported to another package called [rsam](https://github.com/yonicd/rsam). our intention is to remove `remedy::set_hotkeys` from this package to make it more CRAN compliant.

we will probably keep the suggested hotkeys still as part of the package, but you can use them to run in `rsam`, via its [api](https://github.com/yonicd/rsam#set-keyboard-shortcut-for-addins).

**Comment by aoles** [comment]
Thanks a lot for your prompt answer, I managed to set the keys like so:

```r
hotkeys <- remedy::remedy_opts$get("hotkeys")
rsam::set_shortcut(sprintf('remedy::%sr',names(hotkeys)), hotkeys)
```

**Comment by yonicd** [comment]
that looks right. glad it works :)

**Comment by ratnanil** [comment]
I cannot actually find the package `rsam`.. is this package supposed to be on CRAN or Github?
