### ISSUE TITLE
Chunck option in remedy not showing

### ISSUE THREAD

**Issue by sumandoc** [ThinkR-open/remedy#4]
Hi there,

Your package really accelerates working in Rmarkdown. It has made life lot easier.
As I also work with Perl 6 along with R, my work would be easy if I can make code chunk option from

![](https://i.imgur.com/ka1pmd7.png)

to

![](https://i.imgur.com/dZFJjMc.png)

For what I mean, [see here](https://github.com/sumandoc/Getting-Started-with-Perl-6/blob/master/Week-6/handling_text_perl_6.Rmd).

To make this happen what I did was cloned and [edited this file](https://github.com/ThinkR-open/remedy/blob/master/R/chunkizer.R).

I edited the line 11 of that file from

`rstudioapi::insertText(location = a$selection[[1]]$range, text = paste0("```{r}\n", a$selection[[1]]$text, "\n```"))` 
to

`rstudioapi::insertText(location = a$selection[[1]]$range, text = paste0('```{perl, engine.path="perl6"}\n', a$selection[[1]]$text, '\n```'))` 

and after that installed the local package with `devtools::install` command. Though it installs without any error, however the remedy options don't pop in `Addins` in RStudio.

I am on Windows 10 64 bit with RStudio `Version 1.1.350 – © 2009-2017 RStudio, Inc.`
For my needs I have made my [own docker image too](https://hub.docker.com/r/sumdoc/p6rstudio/).

What could I be missing?

Best,
Suman

**Comment by ColinFay** [comment]
Hi Suman ! 

Glad to hear you enjoyed our package :) 

You've indeed edited the right file. I've tried your solution and it words on my machine with a simple `devtools::load_all()` : 

![perl](https://user-images.githubusercontent.com/17936236/30328775-a2523098-97d0-11e7-80d8-2690f7b3d970.gif)

Here are some things that might be causing this issue: 
- Your modified .R is not saved, so `load_all` doesn't see it. 
- Your might need to rebuild the package (I think it's ctrl shift B on windows) 
- Sometimes RStudio addins only refresh when RStudio is closed and open back 

If you've written your own .R files, be sure to add the name of your new function in inst/rstudio/addins.dcf 

Best, 
Colin

**Comment by sumandoc** [comment]
Hi Colin,

Thanks for your help.
I forked your repo and implemented RChunk and Perl6Chunk separately.
Will you just look at it and point if I have made errors. 
This [is the repo](https://github.com/sumandoc/remedy).


Thanks,
Suman

**Comment by ColinFay** [comment]
Hi, 

Please check the PR I just made on your repo. 

Best, 
Colin
