### ISSUE TITLE
Insert Latex Equation Skeleton

### ISSUE THREAD

**Issue by jpiaskowski** [ThinkR-open/remedy#43]
I'm just looking for a quick hotkey-enabled way to insert a latex equation into an RMarkdown file. I looked at your R code a bit. This might work? I'm not sure.

LtxEq <- function() 
  enclose("begin{equation}\n\n", "end{equation}\n")

Or maybe with fewer line breaks.

**Comment by yonicd** [comment]
that is already an addin in [bookdown](https://bookdown.org/yihui/bookdown/rstudio-ide.html)

**Comment by ColinFay** [comment]
The fact that bookdown opens a widget makes me feel like it's not exactly the same feature 🤔

**Comment by yonicd** [comment]
latex is tricky in rmd.

you can take this many places. 

`$*$`
`$$*$$`
`begin{equation}`
`begin{array}` 
`begin{table}` (texPreview)
`begin{tabular}` (texPreview)

maybe a spinoff.... remedy.tex :)

**Comment by ColinFay** [comment]
This is exactly what I've been thinking: maybe another package is needed. It would do the same thing as {remedy}, except that it is centered on inserting LaTeX elements. 

How does it sound to you @jpiaskowski ?

**Comment by yonicd** [comment]
here is a [repo](https://github.com/yonicd/texsnippets) with those boiler plates as snippets.
