### ISSUE TITLE
Clean pkgdown

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/remedy#50]
The "docs" folder of pkgdown should not appear in the master.  
This requires to change links to images/gif in the documentation because they won't be copied. A way is to store images in "man/figures" instead of "readme_gif" as this folder will be automatically copied. But this won't work for the Readme on gitub.  
Another way is to use raw links of github.

**Comment by yonicd** [comment]
docs dir is listed in Rbuildignore and is needed in the master to deploy on success from travis into gh-pages. Moving it out of master may make the clone lighter, but not sure by how much and will make the repository much more complicated than needed to maintain.

**Comment by statnmap** [comment]
You can let travis care about the creation of the "docs" folder in the gh-page branch. This is what is recommended here: https://www.datacamp.com/community/tutorials/cd-package-docs-pkgdown-travis  
This is also what I did for https://github.com/ThinkR-open/attachment or for https://github.com/marionlouveaux/mgx2r (that has images)  
My pull request (https://github.com/ThinkR-open/remedy/pull/49) cleaned this "docs" folder and moved images in the place where pkgdown can still compile.  
I tried it locally, it should also work in combination with Travis.

**Comment by statnmap** [comment]
To sum up:  
- in your current implementation, if you want your pkgdown and the Readme to work correctly, you have to copy gif in 2 places: "readme_gif" and "docs/readme_gif". This is the reason why the last gif added are on the Readme but not on the pkgdown.  
- Travis is building himself the pkgdown pages and store them in branch "gh-page", which mean that the content of the "docs" folder inside the master is unecessary as travis is creating it in the "gh-pages" branch. And this branch is the one used by github to render the website.
- In the way I propose in the pull request, I propose to store images/gif inside a folder named "reference/figures". The content of this folder will be copied inside the "docs" folder when bulding pkgdown. Moreover, the content of this folder is accessible by github. In the code of the readme, you can add figures like this: 

```r
knitr::include_graphics("reference/figures/thinkr-hex-remedy.png")
```
but original ![]("reference/figures/thinkr-hex-remedy.png") should also continue to work. Difference is that you can choose the position, size, ... with the chunk options.

This will prevent you to copy images/gif on 2 different places, this also avoid you to build site before sending to github (although this was not necessary before) . So I do not see what would be more complicated to maintain ?

By the way, the PR also contains an hex for the package, which is the most important thing for R packages nowadays, even more when they are now available on CRAN ! :smiley:   
If the pkgdown fails to be created on github page, I will find out how to repair this...

**Comment by yonicd** [comment]
is this format working already on a branch that can deploy pkgdown?

**Comment by statnmap** [comment]
Not for {remedy} because it is specified in the .travis.yml that only "master" can be used to deploy. But it works in the other packages for which I worked like this:   
- https://github.com/ThinkR-open/attachment 
- https://github.com/marionlouveaux/mgx2r (that has images, also in the vignette)
- https://github.com/marionlouveaux/mamut2r 
- https://github.com/statnmap/SDMSelect (that has images too, also in the vignette)

In the case of package with images in the vignette, I put images in "inst" so that they can be called with `system.file()` in the vignette. And I use URL to raw image of github to show images in Readme and pkgdown. This is another way of doing it.

**Comment by yonicd** [comment]
i dont think we want the gifs in the inst, they can live on another branch if needed and called via anchors in the docs.

**Comment by statnmap** [comment]
True. I had to put them here because the vignettes needs to be run locally on your computer. But in the case of {remedy}, a vignette is not really necessary for a package like this with addins. The github readme is enough.

**Comment by statnmap** [comment]
However, I just remarked that I did not put "reference" directory in the .Rbuildignore, which means it is included in the package, which is not necessary.   
I can add it.

**Comment by yonicd** [comment]
ok. so where are we on the PR, i'm confused.

**Comment by statnmap** [comment]
The PR is not supposed to affect the package build itself.  
It will only affect the github repository:  

- Removes "docs" in the master
- Lists "docs" in ".gitignore" so that you can try to build the pkgdown locally but it won't be send to the repository
- Moves "readme_gif" to "reference/figures/"
- Lists "reference/figures/" to ".Rbuildignore"
- Changes path to gif in the Readme to work both in github readme and in pkgdown
- Adds an hex image to the readme (Approved by the ThinkR team)
- Increase version in NEWS.md to 0.1.0.9000

I created a new branch and a unique clean commit, thus a new pull request #51

**Comment by statnmap** [comment]
Build worked correctly on travis. The pkgdown page is up-to-date !  
Pfiou ! My reputation is still intact ! ;-)
