### ISSUE TITLE
option to open urls in new tab?

### ISSUE THREAD

**Issue by zoowalk** [ThinkR-open/remedy#64]
**Is your feature request related to a problem? Please describe.**
I am regularly using `remedy`'s RStudio add-in including the `url `function. As it is, the created link will open the linked page in the same browser window. This is not always intended, and the url has to be manually modified if one wants the link to get opened in a new tab.

**Describe the solution you'd like**
It would be great to have a function e.g. `url_external `or an option to `url `in `remedy `which specifies that the link has to open in a new tab.

**Describe alternatives you've considered**
Manual modification of link, which can be cumbersome.

Many thanks!

**Comment by yonicd** [comment]
this should work for you `[Link](https://example.org/){target="_blank"}`, i'm not sure how the addin can be modified since the user would have to pass an argument to add `{target="_blank"}`
