### ISSUE TITLE
Feature Request: Ability to inline latex?

### ISSUE THREAD

**Issue by dylanjm** [ThinkR-open/remedy#8]
A great feature would be able to quickly denote inline LaTeX.

**Comment by ColinFay** [comment]
Sounds like a neat idea 💡 !

Not a LaTeX user myself, so when you’re talking about inline latex you’re referring to equation?  

Do you know where I could find an exhaustive list of these?

**Comment by dylanjm** [comment]
@ColinFay Not quite sure what you mean by an exhaustive list.

When writing in your `.rmd` you can denote inline LaTeX by just placing `$` at the beginning and end of your equation. So similarly to the `__bold__` shortcut you can just append the line with `$LaTeX$`

So for instance:

```
This is my analysis in my .rmd file!

__equation:__ $\frac{5}{8} + 2$
```

**Comment by ColinFay** [comment]
Ow, I got it, nice idea! 

I first understood you suggested a shortcut for \int, \tan, and so and on so forth (as I said, not a LaTeX user myself :), so thanks for that), which seemed to me like a complexe feature. 

So, this being said, I'm working on it!

**Comment by dylanjm** [comment]
Sweet!, That's awesome!

**Comment by ColinFay** [comment]
Hi @dylanjm 

Just pushed the new feature. Can you try and tell me if this is what you suggested? 

(You will have to reinstall the package from GitHub) 

![latex](https://user-images.githubusercontent.com/17936236/30683174-a1c37316-9eac-11e7-93fb-29ba6c8891b8.gif)

Thanks again for the suggestion, 
Colin

**Comment by dylanjm** [comment]
@ColinFay That works perfectly! That's awesome. Thank you so much!

**Comment by ColinFay** [comment]
You're welcome! 
Glad to here it helps :)

Best, 
Colin
